interface:
  customerProvision: "CustomerProvision"
customerProvision:
  xsd: "xsd/request/CustomerProvision_request_v2.xsd"
error:
  uri: http://192.168.40.14:31659/dynamicConfig/spain/td/error
dynamicRouting:
  uri: http://192.168.40.14:31659/dynamicConfig/spain/td
server:
  port: 8085
