server:
 port: 8081

configFile:
 unica:
  credential:
   td:
    path: src/main/resources/mapConfig/
    name: Credentials_UNICA_TD.json
  td:
   path: src/main/resources/mapConfig/
   name: DynamicRouting_UNICA_TD.json
  bu:
   path: src/main/resources/mapConfig/
   name: DynamicRouting_UNICA_BU.json
  error:
   td:
     path: src/main/resources/mapConfig/
     name: Errors_UNICA_TD.json
   bu:
     path: src/main/resources/mapConfig/
     name: Errors_UNICA_BU.json   
 spain:
  td:
   path: src/main/resources/mapConfig/
   name: DynamicRouting_SPAIN_TD.json
  bu:
   path: src/main/resources/mapConfig/
   name: DynamicRouting_SPAIN_BU.json
