server:
 port: 8889

webservice:
 identityManagement:
  uri: "/ws"
  targetNamespace: "http://www.telefonica.com/BU_RegistrationService/Import"
  xsd: "wsdl/southbound/BU_RegistrationService/GetAccountForDevice.xsd"
 
dynamicRouting:
  uri:
